apiVersion: apps/v1
kind: Deployment
metadata:
    name: finaltest35-admin-backend-test-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: finaltest35-admin-backend-test-backend
    template:
        metadata:
            labels:
                app: finaltest35-admin-backend-test-backend
        spec:
            imagePullSecrets:
                - name: dockerhub-secret
            containers:
                - name: finaltest35-admin-backend-test-backend
                    image: devopspaxarisglobalrepo/finaltest35-admin-backend-test-backend:latest
                    imagePullPolicy: Always
                    ports:
                        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: finaltest35-admin-backend-test-backend
spec:
    selector:
        app: finaltest35-admin-backend-test-backend
    ports:
        - port: 8080
            targetPort: 8080
    type: ClusterIP
